export type MenuEvent =
  | 'new-project'
  | 'switch-project'
  | 'add-repositories'
  | 'rename-project'
  | 'remove-project'
  | 'show-preferences'
  | 'open-working-directory'
  | 'show-about'
  | 'log-settings'
  | 'reset-settings'
  | 'boomtown'
  | 'open-external-editor'
