export type MenuIDs =
  | 'about'
  | 'add-repositories'
  | 'new-project'
  | 'open-external-editor'
  | 'open-working-directory'
  | 'preferences'
  | 'refresh-project'
  | 'remove-project'
  | 'rename-project'
  | 'rerun-last'
  | 'run-project'
  | 'stop-project'
