name: Publish website

on:
  push:
    branches:
    - chore/refactor

jobs:
  publish:
    name: Publish website
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and publish
      run: cd docs && ./deploy.sh
