name: Publish website

on:
  push:
    branches:
    - chore/refactor

jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Build and publish
      run: ls -la && ./deploy.sh
