name: Release

on:
  push:
    branches:
    - master

jobs:
  release:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: System info (macOS)
      if: matrix.os == 'macOS-latest'
      run: sw_vers
    - name: System info (Windows)
      if: matrix.os == 'windows-latest'
      run: systeminfo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test
      env:
        CI: true
    - name: Release
      run: yarn release
      env:
        CI: true
        CSC_LINK: ${{ secrets.macOSDeveloperCertificate_base64 }}
        CSC_KEY_PASSWORD: ${{ secrets.macOSDeveloperCertificate_password }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        WIN_CSC_LINK: ${{ secrets.CodeSigningCertificate_base64 }}
        WIN_CSC_KEY_PASSWORD: ${{ secrets.CodeSigningCertificate_password }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn run clean && yarn run build
    - name: Publish
      working-directory: docs/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git init
        git add -A
        git commit -m 'Deploy Lode website'
        git push -f https://github-actions:$GITHUB_TOKEN@github.com/lodeapp/lode master:gh-pages
